# Generated by Django 5.2.10 on 2026-02-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Not Paid', 'Not Paid'), ('Shipped', 'Shipped'), ('Ready To Ship', 'Ready To Ship'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Not Paid', max_length=20),
        ),
    ]
