# Generated by Django 5.2.10 on 2026-02-13 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='toal_price',
            new_name='total_price',
        ),
    ]
